server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user # 当前路由的唯一标识
          uri: lb://user # 路由的目标微服务,lb:代表负载均衡，user:代表服务id
          predicates:
            - Path=/user/**

        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
      default-filters: #默认过滤器，全局生效

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
