server:
  port: 8080
spring:
  application:
    name: consumer
eureka:
  client:
    #将服务的列表备份缓存到本地 30秒一次
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka, http://127.0.0.1:10087/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    # 自定义实例的id，规则为 ip地址:app名称:服务的端口号
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
ribbon:
  eager-load:
    clients: user  #设置服务的名称
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 2000  #设置超时时间
